const Joi = require("joi");
'use strict';
/**
 *
 * @param sequelize
 * @param DataTypes
 * @returns {Model|*|void}
 * AUTO GENERATED BY BOTTOM COMMAND
 */
module.exports = (sequelize, DataTypes) => {
    const Plan = sequelize.define('Plan', {
        name: DataTypes.STRING,
        price: DataTypes.FLOAT,
        type: DataTypes.STRING,
        userId: DataTypes.INTEGER
    }, {});
    Plan.associate = function (models) {
        // associations can be defined here
    };
    return Plan;
};


module.exports.PlanValidationSchema = Joi.object().keys({
    name: Joi.required(),
    price: Joi.number().positive().allow(0).required(),
    type: Joi.string().valid("monthly", "yearly").required(),
    userId: Joi.number().positive().required()
})


module.exports.PlanTest = Joi.object().keys({}); //use only in development to omit verification


//sequelize model:generate --name Plan --attributes name:string,price:float,type:string,userId:integer --force